#!/usr/bin/env bash
export DEBIAN_FRONTEND=noninteractive

installpkg(){
    dpkg-query --status $1 >/dev/null || apt-get install -y $1
}

apt-get update
installpkg php5
installpkg php5-mysql
installpkg redis-server
installpkg nodejs
installpkg npm
installpkg mysql-server
installpkg apache2-utils
installpkg apache2-suexec-custom


echo "ServerName localhost" > /etc/apache2/conf-enabled/servername.conf
a2enmod suexec
a2dissite 000-default.conf
cp /tmp/001-imoneytest.conf /etc/apache2/sites-available
a2ensite  001-imoneytest.conf
service apache2 restart

bootstrapdb(){
    cat <<EOF | mysql -uroot
    DROP DATABASE IF EXISTS imoney;
    CREATE DATABASE imoney;
    USE imoney;
    CREATE TABLE imoney (
      id int NOT NULL auto_increment,
      name varchar(255),
      mobno varchar(20),
      email varchar(255),
      auth_token varchar(60),
      created_at DATETIME,
      PRIMARY KEY(id),
      KEY created_at_idx (created_at)
    ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
EOF
}
bootstrapdb

populate_db() {
    /tmp/populate_db 10000000| mysql -u root imoney
}
populate_db
